Repository PrunaAI/pruna, pull requests merged in 2025-05, with the labels that each got.

#95 chore: update `huggingface-hub` dependency to version `>=0.30.0` with extras `hf-xet`
  pyproject.toml
Labels: enhancement

#103 feat: add device validation utility for improved device management
  src/pruna/config/smash_config.py
  src/pruna/engine/utils.py
  tests/engine/test_device.py
Labels: bug

#98 fix: enhance model saving functionality to load multiple JSON configs present in diffusers
  src/pruna/engine/hf_hub_utils/model_card_template.md
  src/pruna/engine/save.py
  tests/conftest.py
  tests/engine/test_load.py
  tests/engine/test_save.py
Labels: bug

#143 reafactor: remove deprecated awq algorithm
  .github/workflows/external_contributions_tests.yaml
  pyproject.toml
  src/pruna/algorithms/quantization/huggingface_awq.py
  src/pruna/config/smash_config.py
  src/pruna/engine/handler/handler_utils.py
  src/pruna/engine/load.py
  src/pruna/engine/save.py
  tests/algorithms/testers/quantization.py
Labels: codex
